### ISSUE TITLE
module "xmlrpc" not found

### ISSUE THREAD

**Issue by 0xresetti** [20urc3/Sekiryu#2]
When running the script on Ghidra, the module "xmlrpc" is not found.

I looked around for it, but cant install it via pip and cant find a source for it anywhere for manual install.

**Comment by tcccorp** [comment]
hello,  

replace 
import os, xmlrpc, subprocess, re, sys
from time import sleep
from xmlrpc.client import ServerProxy

by 
import os, xmlrpclib, subprocess, re, sys
from time import sleep
from xmlrpclib.client import ServerProxy

I made another modification on  server.py ( maybe beacause I'm under windows ). I added api_key()  on analyse_GPT(string) def 

![image](https://user-images.githubusercontent.com/23424205/226107954-4fb6ca22-c8ab-4f64-a330-399bbc4bd170.png)


last thing,  check on your chatGPT account if  you have a credit card  because you need credit to use this API :)

at the end it works :)
![image](https://user-images.githubusercontent.com/23424205/226108120-d009d363-fdc6-493d-9d4d-136d20c75fc2.png)

**Comment by 20urc3** [comment]
Hi!
- Problem fixed in the next release
- You don't need credit card for the API use, at least i didn't.
